import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { LanguageProvider } from '@/lib/i18n/context'
import { LanguageSwitcher } from '@/components/ui/language-switcher'
import { CurrencyProvider } from '@/lib/currency/context'



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6002876774605337" crossOrigin="anonymous"></script>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="g_id_onload"
          data-client_id={process.env.GOOGLE_CLIENT_ID}
          data-login_uri={`${process.env.NEXT_PUBLIC_APP_URL || ''}/api/auth/callback/google`}
          data-auto_prompt="false">
        </div>
        <LanguageProvider>
          <CurrencyProvider>
            {children}
            <LanguageSwitcher />
          </CurrencyProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
