-- Enable Row Level Security on all tables
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "securities_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_holdings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stocks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_histories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "simulations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kis_stock_masters" ENABLE ROW LEVEL SECURITY;