name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
          DIRECT_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
        run: npx prisma generate

      - name: Build static site
        run: npm run build      # output: 'export' 설정으로 out 폴더 생성

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out           # Next가 만든 정적 파일 폴더
          branch: gh-pages
